// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.5.1
// source: props/props.proto

package props

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *PropsInfo) Reset() {
	*x = PropsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_props_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropsInfo) ProtoMessage() {}

func (x *PropsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_props_props_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropsInfo.ProtoReflect.Descriptor instead.
func (*PropsInfo) Descriptor() ([]byte, []int) {
	return file_props_props_proto_rawDescGZIP(), []int{0}
}

func (x *PropsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropsInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type AddPropsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropsList []*PropsInfo `protobuf:"bytes,1,rep,name=props_list,json=propsList,proto3" json:"props_list,omitempty"`
}

func (x *AddPropsRequest) Reset() {
	*x = AddPropsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_props_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPropsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPropsRequest) ProtoMessage() {}

func (x *AddPropsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_props_props_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPropsRequest.ProtoReflect.Descriptor instead.
func (*AddPropsRequest) Descriptor() ([]byte, []int) {
	return file_props_props_proto_rawDescGZIP(), []int{1}
}

func (x *AddPropsRequest) GetPropsList() []*PropsInfo {
	if x != nil {
		return x.PropsList
	}
	return nil
}

type AddPropsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPropsResponse) Reset() {
	*x = AddPropsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_props_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPropsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPropsResponse) ProtoMessage() {}

func (x *AddPropsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_props_props_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPropsResponse.ProtoReflect.Descriptor instead.
func (*AddPropsResponse) Descriptor() ([]byte, []int) {
	return file_props_props_proto_rawDescGZIP(), []int{2}
}

type UpdatePropsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropsId int32 `protobuf:"varint,1,opt,name=props_id,json=propsId,proto3" json:"props_id,omitempty"`
}

func (x *UpdatePropsRequest) Reset() {
	*x = UpdatePropsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_props_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePropsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropsRequest) ProtoMessage() {}

func (x *UpdatePropsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_props_props_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePropsRequest) Descriptor() ([]byte, []int) {
	return file_props_props_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePropsRequest) GetPropsId() int32 {
	if x != nil {
		return x.PropsId
	}
	return 0
}

type UpdatePropsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePropsResponse) Reset() {
	*x = UpdatePropsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_props_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePropsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropsResponse) ProtoMessage() {}

func (x *UpdatePropsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_props_props_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePropsResponse) Descriptor() ([]byte, []int) {
	return file_props_props_proto_rawDescGZIP(), []int{4}
}

var File_props_props_proto protoreflect.FileDescriptor

var file_props_props_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x22, 0x3c, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x70, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x42, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x50,
	0x72, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x70, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10,
	0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2f, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x49,
	0x64, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x63, 0x5f, 0x6e, 0x66, 0x74, 0x2f, 0x6b, 0x69,
	0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_props_props_proto_rawDescOnce sync.Once
	file_props_props_proto_rawDescData = file_props_props_proto_rawDesc
)

func file_props_props_proto_rawDescGZIP() []byte {
	file_props_props_proto_rawDescOnce.Do(func() {
		file_props_props_proto_rawDescData = protoimpl.X.CompressGZIP(file_props_props_proto_rawDescData)
	})
	return file_props_props_proto_rawDescData
}

var file_props_props_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_props_props_proto_goTypes = []interface{}{
	(*PropsInfo)(nil),           // 0: props.PropsInfo
	(*AddPropsRequest)(nil),     // 1: props.AddPropsRequest
	(*AddPropsResponse)(nil),    // 2: props.AddPropsResponse
	(*UpdatePropsRequest)(nil),  // 3: props.UpdatePropsRequest
	(*UpdatePropsResponse)(nil), // 4: props.UpdatePropsResponse
}
var file_props_props_proto_depIdxs = []int32{
	0, // 0: props.AddPropsRequest.props_list:type_name -> props.PropsInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_props_props_proto_init() }
func file_props_props_proto_init() {
	if File_props_props_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_props_props_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_props_props_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPropsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_props_props_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPropsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_props_props_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePropsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_props_props_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePropsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_props_props_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_props_props_proto_goTypes,
		DependencyIndexes: file_props_props_proto_depIdxs,
		MessageInfos:      file_props_props_proto_msgTypes,
	}.Build()
	File_props_props_proto = out.File
	file_props_props_proto_rawDesc = nil
	file_props_props_proto_goTypes = nil
	file_props_props_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.3.2. DO NOT EDIT.
