// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: credits/credits.proto

package credits

import (
	context "context"
	base "github.com/mc_nft/kitex_gen/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditsSource int32

const (
	CreditsSource_CreditsSource_Unknown          CreditsSource = 0
	CreditsSource_CreditsSource_CollectionChange CreditsSource = 1 // 藏品变更
	CreditsSource_CreditsSource_AdminModify      CreditsSource = 2 // 系统修改
)

// Enum value maps for CreditsSource.
var (
	CreditsSource_name = map[int32]string{
		0: "CreditsSource_Unknown",
		1: "CreditsSource_CollectionChange",
		2: "CreditsSource_AdminModify",
	}
	CreditsSource_value = map[string]int32{
		"CreditsSource_Unknown":          0,
		"CreditsSource_CollectionChange": 1,
		"CreditsSource_AdminModify":      2,
	}
)

func (x CreditsSource) Enum() *CreditsSource {
	p := new(CreditsSource)
	*p = x
	return p
}

func (x CreditsSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreditsSource) Descriptor() protoreflect.EnumDescriptor {
	return file_credits_credits_proto_enumTypes[0].Descriptor()
}

func (CreditsSource) Type() protoreflect.EnumType {
	return &file_credits_credits_proto_enumTypes[0]
}

func (x CreditsSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreditsSource.Descriptor instead.
func (CreditsSource) EnumDescriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{0}
}

type CreditsChangeType int32

const (
	CreditsChangeType_CreditsChangeType_Unknown  CreditsChangeType = 0
	CreditsChangeType_CreditsChangeType_Positive CreditsChangeType = 1 // 正趋势
	CreditsChangeType_CreditsChangeType_Negative CreditsChangeType = 2 // 负趋势
)

// Enum value maps for CreditsChangeType.
var (
	CreditsChangeType_name = map[int32]string{
		0: "CreditsChangeType_Unknown",
		1: "CreditsChangeType_Positive",
		2: "CreditsChangeType_Negative",
	}
	CreditsChangeType_value = map[string]int32{
		"CreditsChangeType_Unknown":  0,
		"CreditsChangeType_Positive": 1,
		"CreditsChangeType_Negative": 2,
	}
)

func (x CreditsChangeType) Enum() *CreditsChangeType {
	p := new(CreditsChangeType)
	*p = x
	return p
}

func (x CreditsChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreditsChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_credits_credits_proto_enumTypes[1].Descriptor()
}

func (CreditsChangeType) Type() protoreflect.EnumType {
	return &file_credits_credits_proto_enumTypes[1]
}

func (x CreditsChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreditsChangeType.Descriptor instead.
func (CreditsChangeType) EnumDescriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{1}
}

type AddOrUpdateCreditsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        int64             `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                // 用户uid
	Source     CreditsSource     `protobuf:"varint,2,opt,name=source,proto3,enum=credits.CreditsSource" json:"source,omitempty"`                               // 积分来源
	ChangeType CreditsChangeType `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3,enum=credits.CreditsChangeType" json:"change_type,omitempty"` // 变更类型
	Amount     int32             `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                                          // 变更大小
	Record     string            `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"`                                                           // 变更来源记录， 如藏品id
	Base       *base.Base        `protobuf:"bytes,255,opt,name=Base,proto3" json:"Base,omitempty"`
}

func (x *AddOrUpdateCreditsRequest) Reset() {
	*x = AddOrUpdateCreditsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credits_credits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrUpdateCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateCreditsRequest) ProtoMessage() {}

func (x *AddOrUpdateCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credits_credits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateCreditsRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdateCreditsRequest) Descriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrUpdateCreditsRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddOrUpdateCreditsRequest) GetSource() CreditsSource {
	if x != nil {
		return x.Source
	}
	return CreditsSource_CreditsSource_Unknown
}

func (x *AddOrUpdateCreditsRequest) GetChangeType() CreditsChangeType {
	if x != nil {
		return x.ChangeType
	}
	return CreditsChangeType_CreditsChangeType_Unknown
}

func (x *AddOrUpdateCreditsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddOrUpdateCreditsRequest) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

func (x *AddOrUpdateCreditsRequest) GetBase() *base.Base {
	if x != nil {
		return x.Base
	}
	return nil
}

type AddOrUpdateCreditsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *base.BaseResp `protobuf:"bytes,255,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *AddOrUpdateCreditsResponse) Reset() {
	*x = AddOrUpdateCreditsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credits_credits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrUpdateCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateCreditsResponse) ProtoMessage() {}

func (x *AddOrUpdateCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credits_credits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateCreditsResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdateCreditsResponse) Descriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrUpdateCreditsResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GetUserCreditsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64      `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 用户uid
	Base *base.Base `protobuf:"bytes,255,opt,name=Base,proto3" json:"Base,omitempty"`
}

func (x *GetUserCreditsRequest) Reset() {
	*x = GetUserCreditsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credits_credits_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCreditsRequest) ProtoMessage() {}

func (x *GetUserCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credits_credits_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCreditsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCreditsRequest) Descriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserCreditsRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserCreditsRequest) GetBase() *base.Base {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetUserCreditsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreditsAmount int32          `protobuf:"varint,1,opt,name=credits_amount,json=creditsAmount,proto3" json:"credits_amount,omitempty"` // 积分数量
	BaseResp      *base.BaseResp `protobuf:"bytes,255,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *GetUserCreditsResponse) Reset() {
	*x = GetUserCreditsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credits_credits_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCreditsResponse) ProtoMessage() {}

func (x *GetUserCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credits_credits_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCreditsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCreditsResponse) Descriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserCreditsResponse) GetCreditsAmount() int32 {
	if x != nil {
		return x.CreditsAmount
	}
	return 0
}

func (x *GetUserCreditsResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type RankItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                              // 用户uid
	NickName  string `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`     // 用户昵称
	Avatar    string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                         // 用户头像
	RankIndex int32  `protobuf:"varint,4,opt,name=rank_index,json=rankIndex,proto3" json:"rank_index,omitempty"` // 排行名次
	Value     int32  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`                          // 排行分值
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credits_credits_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_credits_credits_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{4}
}

func (x *RankItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RankItem) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *RankItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RankItem) GetRankIndex() int32 {
	if x != nil {
		return x.RankIndex
	}
	return 0
}

func (x *RankItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetCreditsRankRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *base.Base `protobuf:"bytes,255,opt,name=Base,proto3" json:"Base,omitempty"`
}

func (x *GetCreditsRankRequest) Reset() {
	*x = GetCreditsRankRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credits_credits_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCreditsRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditsRankRequest) ProtoMessage() {}

func (x *GetCreditsRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credits_credits_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditsRankRequest.ProtoReflect.Descriptor instead.
func (*GetCreditsRankRequest) Descriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{5}
}

func (x *GetCreditsRankRequest) GetBase() *base.Base {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetCreditsRankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items    []*RankItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	BaseResp *base.BaseResp `protobuf:"bytes,255,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *GetCreditsRankResponse) Reset() {
	*x = GetCreditsRankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credits_credits_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCreditsRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditsRankResponse) ProtoMessage() {}

func (x *GetCreditsRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credits_credits_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditsRankResponse.ProtoReflect.Descriptor instead.
func (*GetCreditsRankResponse) Descriptor() ([]byte, []int) {
	return file_credits_credits_proto_rawDescGZIP(), []int{6}
}

func (x *GetCreditsRankResponse) GetItems() []*RankItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCreditsRankResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_credits_credits_proto protoreflect.FileDescriptor

var file_credits_credits_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73,
	0x1a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xeb, 0x01, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f,
	0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x22,
	0x49, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0xff, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x22, 0x6c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x5f, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x6b,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x61,
	0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x52, 0x61, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0xff,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x22, 0x6e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x73, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2a, 0x6d, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x10, 0x02, 0x2a, 0x72, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x43,
	0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x4e, 0x65, 0x67, 0x61, 0x74, 0x69, 0x76, 0x65, 0x10, 0x02, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x63, 0x5f, 0x6e, 0x66, 0x74, 0x2f,
	0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_credits_credits_proto_rawDescOnce sync.Once
	file_credits_credits_proto_rawDescData = file_credits_credits_proto_rawDesc
)

func file_credits_credits_proto_rawDescGZIP() []byte {
	file_credits_credits_proto_rawDescOnce.Do(func() {
		file_credits_credits_proto_rawDescData = protoimpl.X.CompressGZIP(file_credits_credits_proto_rawDescData)
	})
	return file_credits_credits_proto_rawDescData
}

var file_credits_credits_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_credits_credits_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_credits_credits_proto_goTypes = []interface{}{
	(CreditsSource)(0),                 // 0: credits.CreditsSource
	(CreditsChangeType)(0),             // 1: credits.CreditsChangeType
	(*AddOrUpdateCreditsRequest)(nil),  // 2: credits.AddOrUpdateCreditsRequest
	(*AddOrUpdateCreditsResponse)(nil), // 3: credits.AddOrUpdateCreditsResponse
	(*GetUserCreditsRequest)(nil),      // 4: credits.GetUserCreditsRequest
	(*GetUserCreditsResponse)(nil),     // 5: credits.GetUserCreditsResponse
	(*RankItem)(nil),                   // 6: credits.RankItem
	(*GetCreditsRankRequest)(nil),      // 7: credits.GetCreditsRankRequest
	(*GetCreditsRankResponse)(nil),     // 8: credits.GetCreditsRankResponse
	(*base.Base)(nil),                  // 9: base.Base
	(*base.BaseResp)(nil),              // 10: base.BaseResp
}
var file_credits_credits_proto_depIdxs = []int32{
	0,  // 0: credits.AddOrUpdateCreditsRequest.source:type_name -> credits.CreditsSource
	1,  // 1: credits.AddOrUpdateCreditsRequest.change_type:type_name -> credits.CreditsChangeType
	9,  // 2: credits.AddOrUpdateCreditsRequest.Base:type_name -> base.Base
	10, // 3: credits.AddOrUpdateCreditsResponse.BaseResp:type_name -> base.BaseResp
	9,  // 4: credits.GetUserCreditsRequest.Base:type_name -> base.Base
	10, // 5: credits.GetUserCreditsResponse.BaseResp:type_name -> base.BaseResp
	9,  // 6: credits.GetCreditsRankRequest.Base:type_name -> base.Base
	6,  // 7: credits.GetCreditsRankResponse.items:type_name -> credits.RankItem
	10, // 8: credits.GetCreditsRankResponse.BaseResp:type_name -> base.BaseResp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_credits_credits_proto_init() }
func file_credits_credits_proto_init() {
	if File_credits_credits_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_credits_credits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrUpdateCreditsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credits_credits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrUpdateCreditsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credits_credits_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCreditsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credits_credits_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCreditsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credits_credits_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credits_credits_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCreditsRankRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credits_credits_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCreditsRankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_credits_credits_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_credits_credits_proto_goTypes,
		DependencyIndexes: file_credits_credits_proto_depIdxs,
		EnumInfos:         file_credits_credits_proto_enumTypes,
		MessageInfos:      file_credits_credits_proto_msgTypes,
	}.Build()
	File_credits_credits_proto = out.File
	file_credits_credits_proto_rawDesc = nil
	file_credits_credits_proto_goTypes = nil
	file_credits_credits_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.3.2. DO NOT EDIT.
