// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/mc_nft/dal/model"
)

func newPropsInfo(db *gorm.DB) propsInfo {
	_propsInfo := propsInfo{}

	_propsInfo.propsInfoDo.UseDB(db)
	_propsInfo.propsInfoDo.UseModel(&model.PropsInfo{})

	tableName := _propsInfo.propsInfoDo.TableName()
	_propsInfo.ALL = field.NewField(tableName, "*")
	_propsInfo.ID = field.NewInt64(tableName, "id")
	_propsInfo.PropsID = field.NewInt64(tableName, "props_id")
	_propsInfo.Name = field.NewString(tableName, "name")
	_propsInfo.ImageURL = field.NewString(tableName, "image_url")
	_propsInfo.Type = field.NewInt32(tableName, "type")
	_propsInfo.Desc = field.NewString(tableName, "desc")
	_propsInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_propsInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_propsInfo.fillFieldMap()

	return _propsInfo
}

type propsInfo struct {
	propsInfoDo propsInfoDo

	ALL       field.Field
	ID        field.Int64
	PropsID   field.Int64
	Name      field.String
	ImageURL  field.String
	Type      field.Int32
	Desc      field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p propsInfo) Table(newTableName string) *propsInfo {
	p.propsInfoDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p propsInfo) As(alias string) *propsInfo {
	p.propsInfoDo.DO = *(p.propsInfoDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *propsInfo) updateTableName(table string) *propsInfo {
	p.ALL = field.NewField(table, "*")
	p.ID = field.NewInt64(table, "id")
	p.PropsID = field.NewInt64(table, "props_id")
	p.Name = field.NewString(table, "name")
	p.ImageURL = field.NewString(table, "image_url")
	p.Type = field.NewInt32(table, "type")
	p.Desc = field.NewString(table, "desc")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *propsInfo) WithContext(ctx context.Context) *propsInfoDo {
	return p.propsInfoDo.WithContext(ctx)
}

func (p propsInfo) TableName() string { return p.propsInfoDo.TableName() }

func (p propsInfo) Alias() string { return p.propsInfoDo.Alias() }

func (p *propsInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *propsInfo) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["props_id"] = p.PropsID
	p.fieldMap["name"] = p.Name
	p.fieldMap["image_url"] = p.ImageURL
	p.fieldMap["type"] = p.Type
	p.fieldMap["desc"] = p.Desc
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p propsInfo) clone(db *gorm.DB) propsInfo {
	p.propsInfoDo.ReplaceDB(db)
	return p
}

type propsInfoDo struct{ gen.DO }

func (p propsInfoDo) Debug() *propsInfoDo {
	return p.withDO(p.DO.Debug())
}

func (p propsInfoDo) WithContext(ctx context.Context) *propsInfoDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p propsInfoDo) ReadDB() *propsInfoDo {
	return p.Clauses(dbresolver.Read)
}

func (p propsInfoDo) WriteDB() *propsInfoDo {
	return p.Clauses(dbresolver.Write)
}

func (p propsInfoDo) Clauses(conds ...clause.Expression) *propsInfoDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p propsInfoDo) Returning(value interface{}, columns ...string) *propsInfoDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p propsInfoDo) Not(conds ...gen.Condition) *propsInfoDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p propsInfoDo) Or(conds ...gen.Condition) *propsInfoDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p propsInfoDo) Select(conds ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p propsInfoDo) Where(conds ...gen.Condition) *propsInfoDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p propsInfoDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *propsInfoDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p propsInfoDo) Order(conds ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p propsInfoDo) Distinct(cols ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p propsInfoDo) Omit(cols ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p propsInfoDo) Join(table schema.Tabler, on ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p propsInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p propsInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p propsInfoDo) Group(cols ...field.Expr) *propsInfoDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p propsInfoDo) Having(conds ...gen.Condition) *propsInfoDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p propsInfoDo) Limit(limit int) *propsInfoDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p propsInfoDo) Offset(offset int) *propsInfoDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p propsInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *propsInfoDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p propsInfoDo) Unscoped() *propsInfoDo {
	return p.withDO(p.DO.Unscoped())
}

func (p propsInfoDo) Create(values ...*model.PropsInfo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p propsInfoDo) CreateInBatches(values []*model.PropsInfo, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p propsInfoDo) Save(values ...*model.PropsInfo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p propsInfoDo) First() (*model.PropsInfo, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropsInfo), nil
	}
}

func (p propsInfoDo) Take() (*model.PropsInfo, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropsInfo), nil
	}
}

func (p propsInfoDo) Last() (*model.PropsInfo, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropsInfo), nil
	}
}

func (p propsInfoDo) Find() ([]*model.PropsInfo, error) {
	result, err := p.DO.Find()
	return result.([]*model.PropsInfo), err
}

func (p propsInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PropsInfo, err error) {
	buf := make([]*model.PropsInfo, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p propsInfoDo) FindInBatches(result *[]*model.PropsInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p propsInfoDo) Attrs(attrs ...field.AssignExpr) *propsInfoDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p propsInfoDo) Assign(attrs ...field.AssignExpr) *propsInfoDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p propsInfoDo) Joins(fields ...field.RelationField) *propsInfoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p propsInfoDo) Preload(fields ...field.RelationField) *propsInfoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p propsInfoDo) FirstOrInit() (*model.PropsInfo, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropsInfo), nil
	}
}

func (p propsInfoDo) FirstOrCreate() (*model.PropsInfo, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropsInfo), nil
	}
}

func (p propsInfoDo) FindByPage(offset int, limit int) (result []*model.PropsInfo, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p propsInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p propsInfoDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p *propsInfoDo) withDO(do gen.Dao) *propsInfoDo {
	p.DO = *do.(*gen.DO)
	return p
}
