// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCreditsRecord = "credits_record"

// CreditsRecord mapped from table <credits_record>
type CreditsRecord struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	UserID     int64      `gorm:"column:user_id;not null" json:"user_id"`            // 用户id
	CreditsCnt int32      `gorm:"column:credits_cnt;not null" json:"credits_cnt"`    // 用户积分
	Source     int32      `gorm:"column:source;not null" json:"source"`              // 积分来源
	CreatedAt  *time.Time `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt  *time.Time `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
}

// TableName CreditsRecord's table name
func (*CreditsRecord) TableName() string {
	return TableNameCreditsRecord
}
