// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserInfo = "user_info"

// UserInfo mapped from table <user_info>
type UserInfo struct {
	ID               int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`   // 主键id
	Nickname         string     `gorm:"column:nickname;not null" json:"nickname"`            // 用户昵称
	Avatar           string     `gorm:"column:avatar;not null" json:"avatar"`                // 用户头像
	RealName         *string    `gorm:"column:real_name" json:"real_name"`                   // 真实姓名
	IDCard           *string    `gorm:"column:id_card" json:"id_card"`                       // 身份证号
	CertifiedPhone   *string    `gorm:"column:certified_phone" json:"certified_phone"`       // 手机号
	CertifiedTime    *time.Time `gorm:"column:certified_time" json:"certified_time"`         // 认证时间
	IsCertified      int32      `gorm:"column:is_certified;not null" json:"is_certified"`    // 是否实名认证
	ChainAccountID   *string    `gorm:"column:chain_account_id" json:"chain_account_id"`     // 链上账户id
	ChainAccountName *string    `gorm:"column:chain_account_name" json:"chain_account_name"` // 链上账户名
	InviteCode       *string    `gorm:"column:invite_code" json:"invite_code"`               // 邀请码
	ChannelCode      *string    `gorm:"column:channel_code" json:"channel_code"`             // 渠道邀请码
	InviteUserID     *int64     `gorm:"column:invite_user_id" json:"invite_user_id"`         // 邀请人id
	CreditsCnt       int32      `gorm:"column:credits_cnt;not null" json:"credits_cnt"`      // 用户积分
	DiamondCnt       int32      `gorm:"column:diamond_cnt;not null" json:"diamond_cnt"`      // 用户钻石数
	CreatedAt        *time.Time `gorm:"column:created_at" json:"created_at"`                 // 创建时间
	UpdatedAt        *time.Time `gorm:"column:updated_at" json:"updated_at"`                 // 更新时间
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
