// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserProp = "user_props"

// UserProp mapped from table <user_props>
type UserProp struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	UserID    int64      `gorm:"column:user_id;not null" json:"user_id"`            // 用户id
	PropsID   int64      `gorm:"column:props_id;not null" json:"props_id"`          // 道具id
	Num       int32      `gorm:"column:num;not null" json:"num"`                    // 道具数量
	CreatedAt *time.Time `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
}

// TableName UserProp's table name
func (*UserProp) TableName() string {
	return TableNameUserProp
}
