// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVirtualCurrencyRecord = "virtual_currency_record"

// VirtualCurrencyRecord mapped from table <virtual_currency_record>
type VirtualCurrencyRecord struct {
	ID                 int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                // 主键id
	UserID             int64      `gorm:"column:user_id;not null" json:"user_id"`                           // 用户id
	VirtualCurrencyCnt int32      `gorm:"column:virtual_currency_cnt;not null" json:"virtual_currency_cnt"` // 货币变更数量
	Source             int32      `gorm:"column:source;not null" json:"source"`                             // 货币来源
	RecordType         int32      `gorm:"column:record_type;not null" json:"record_type"`                   // 货币记录类型: 发放、消耗、转移
	CreatedAt          *time.Time `gorm:"column:created_at" json:"created_at"`                              // 创建时间
	UpdatedAt          *time.Time `gorm:"column:updated_at" json:"updated_at"`                              // 更新时间
}

// TableName VirtualCurrencyRecord's table name
func (*VirtualCurrencyRecord) TableName() string {
	return TableNameVirtualCurrencyRecord
}
